name: Publish Docker
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mfbx9da4/validate-email-endpoint
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@master
      - name: Publish and Deploy to Heroku
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deep-email-validator/web
          username: _
          password: ${{ secrets.DOCKER_PASSWORD_HEROKU }}
          registry: registry.heroku.com
